#!/usr/bin/env bash
# share_lib: 디버그=로컬 path, 릴리즈/CI=GitHub git (pubspec_overrides.yaml)
#
#   source tool/share_lib_source.sh
#   share_lib_use_local  "$CLIENT_DIR"   # 일상 개발 (기본)
#   share_lib_use_git    "$CLIENT_DIR"   # Xcode Cloud / App Store 릴리즈

SHARE_LIB_GIT_URL="${SHARE_LIB_GIT_URL:-https://github.com/smartcompany/flutter_share_lib.git}"
SHARE_LIB_GIT_REF="${SHARE_LIB_GIT_REF:-main}"

share_lib_overrides_file() {
  echo "${1:?client dir}/pubspec_overrides.yaml"
}

share_lib_use_git() {
  local client_dir="$1"
  local overrides
  overrides="$(share_lib_overrides_file "$client_dir")"
  cat >"$overrides" <<EOF
# Generated by tool/share_lib_source.sh — release / Xcode Cloud
dependency_overrides:
  share_lib:
    git:
      url: ${SHARE_LIB_GIT_URL}
      ref: ${SHARE_LIB_GIT_REF}
EOF
  echo "[share_lib] release → git (${SHARE_LIB_GIT_REF})"
}

share_lib_use_local() {
  local client_dir="$1"
  local overrides
  overrides="$(share_lib_overrides_file "$client_dir")"
  rm -f "$overrides"
  echo "[share_lib] debug → local path (../../flutter_share_lib)"
}
